[metadata]
name = hentailib
version = 0.5.1
author = Onii-Chan
author_email = skobochki.ad@mail.ru
description = Library for easy requests hentai sites
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/SerJo2/hentailib
license = MIT
keywords = hentai, requests, rule34
classifiers =
    Programming Language :: Python :: 3

[options]
python_requires = >=3.9
install_requires =
    requests
